// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4cr0GdPw9dL2vQV2Dlk-AsynfwM44Xg',
    appId: '1:214774081069:web:1602cb36790fe97a597aa4',
    messagingSenderId: '214774081069',
    projectId: 'agropack-f3787',
    authDomain: 'agropack-f3787.firebaseapp.com',
    storageBucket: 'agropack-f3787.firebasestorage.app',
    measurementId: 'G-F9HZ3ELP0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWymA9dNjrfrDEulVoTZMBf_lqyj9qdY',
    appId: '1:214774081069:android:e990e99c7172a669597aa4',
    messagingSenderId: '214774081069',
    projectId: 'agropack-f3787',
    storageBucket: 'agropack-f3787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZ6ZxqY-zKUhWEd-8cIstxk-cdCPSzoM',
    appId: '1:214774081069:ios:2dc70e3f46352ee3597aa4',
    messagingSenderId: '214774081069',
    projectId: 'agropack-f3787',
    storageBucket: 'agropack-f3787.firebasestorage.app',
    iosBundleId: 'com.example.agroPackaging',
  );
}
